kind: pipeline
name: default
steps:
- name: docker:
  image: plugins/docker
  settings:
    repo: jonnrb/oauth2_proxy
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
